preset: symfony

version: 7.4

risky: true

enabled:
  - align_phpdoc
  - alpha_ordered_imports
  - array_indentation
  - const_visibility_required
  - method_argument_space_strict
  - native_constant_invocation
  - native_function_invocation
  - no_useless_return
  - phpdoc_order
  - short_list_syntax
  - ternary_to_null_coalescing
  - void_return

disabled:
  - method_argument_space
  - native_constant_invocation_symfony
  - native_function_invocation_symfony
  - no_superfluous_phpdoc_tags_symfony
  - phpdoc_to_comment
  - phpdoc_var_without_name
